import fs from 'fs'
import {UNIWIND_PACKAGE_NAME} from "../types";

export const buildDtsFile = (dtsPath: string, stringifiedThemes: string) => {
    const oldDtsContent = fs.existsSync(dtsPath)
        ? fs.readFileSync(dtsPath, 'utf-8')
        : ''
    const dtsContent = [
        `// NOTE: This file is generated by ${UNIWIND_PACKAGE_NAME} and it should not be edited manually.`,
        `/// <reference types="${UNIWIND_PACKAGE_NAME}/types" />`,
        '',
        `declare module '${UNIWIND_PACKAGE_NAME}' {`,
        `    export interface UniwindConfig {`,
        `        themes: readonly ${stringifiedThemes}`,
        `    }`,
        `}`,
        '',
        `export {}`,
        '',
    ].join('\n')

    if (oldDtsContent === dtsContent) {
        return
    }

    fs.writeFileSync(dtsPath, dtsContent)
}
